stages:
  - build
  - test
  - deploy
########################################################################################################################
####START####                                     PROJECT LEVEL VARIABLES                                  ####START####
########################################################################################################################
variables:
  DOCKER_DRIVER: overlay2
  DEFAULT_VERUSCOIN_BRANCH: release
  VERUS_VERSION: 1.2.9-4
  VERUSCOIN_VERSION: 1.2.9-4
  KOMODO_VERSION: 0.9.0
  KOMODO_DOWNLOAD_URL: https://github.com/KomodoPlatform/komodo/releases/download
  PIRATE_VERSION: 5.9.0
  PIRATE_DOWNLOAD_URL: https://github.com/PirateNetwork/pirate/releases/download
  BINARY_SOURCE: VerusCoin
  VERUS_APPIMAGE_X64: Verus-Desktop-Testnet-v${VERUS_VERSION}-x86_64.AppImage
  VERUS_APPIMAGE_ARM64: Verus-Desktop-Testnet-v${VERUS_VERSION}-arm64.AppImage
  VERUS_WINDOWS_ZIP: Verus-Desktop-Testnet-Windows-v${VERUS_VERSION}.zip
  VERUS_WINDOWS_NSIS: Verus-Desktop-Testnet-v${VERUS_VERSION}.exe
  VERUS_MACOS: Verus-Desktop-Testnet-v${VERUS_VERSION}.dmg
  GIT_SUBMODULE_STRATEGY: recursive
  POST_COMMENT: "Pipeline Trigger: ${CI_PIPELINE_SOURCE}\n
      Branch: ${CI_COMMIT_REF_NAME}\n
      Commit: https://github.com/VerusCoin/Verus-Desktop/commit/${CI_COMMIT_SHA}\n
      ${CI_COMMIT_MESSAGE}\n"
########################################################################################################################
####END####                                        PROJECT LEVEL VARIABLES                                   ####END####
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####                                          Build Stage                                        ####START#####
########################################################################################################################
########################################################################################################################
####START####                                            LINUX                                             ####START####
########################################################################################################################
build:linux:
  tags: [ "Verus Desktop" ]
  image: asherd/agama-builder
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    KOMODO_CLI_PACKAGE: komodo-${KOMODO_VERSION}-linux.tar.gz
    KOMODO_CLI_SHA256: ed28bce09176c212c1eac9abf9fce41c948ef1199764b03b607a461146952107
    PIRATE_CLI_PACKAGE: pirate-cli-ubuntu2004-v${PIRATE_VERSION}.zip
    PIRATE_CLI_SHA256: 2358e992a6649517f6a72f790105468a22c5ae22302076b06f9c528b7c7c4788
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_LINUX="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Linux/Verus-CLI-Linux-v${VERUSCOIN_VERSION}-x86_64.tar.gz"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/linux64/verusd
    - gsutil cp $STAGING/$VERUS_CLI_LINUX .
    - tar -xzvf Verus-CLI-Linux-v${VERUSCOIN_VERSION}-x86_64.tar.gz --strip=1 --directory assets/bin/linux64/verusd
    - rm Verus-CLI-Linux-v${VERUSCOIN_VERSION}-x86_64.tar.gz
    - mkdir -p assets/bin/linux64/komodod
    - mkdir -p assets/bin/linux64/pirated
    - wget ${KOMODO_DOWNLOAD_URL}/v${KOMODO_VERSION}/${KOMODO_CLI_PACKAGE}
    - echo "${KOMODO_CLI_SHA256} ${KOMODO_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - tar -xzvf ${KOMODO_CLI_PACKAGE} --directory assets/bin/linux64/komodod
    - rm ${KOMODO_CLI_PACKAGE}
    - wget ${PIRATE_DOWNLOAD_URL}/v${PIRATE_VERSION}/${PIRATE_CLI_PACKAGE}
    - echo "${PIRATE_CLI_SHA256} ${PIRATE_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - unzip ${PIRATE_CLI_PACKAGE} -d assets/bin/linux64/pirated
    - rm ${PIRATE_CLI_PACKAGE}
    - sed -i "s/process.env.INFURA_PROJECT_ID/'${INFURA_PROJECT_ID}'/g" keys/infura.js
    - sed -i "s/process.env.ETHERSCAN_API_KEY/'${ETHERSCAN_KEY}'/g" keys/etherscan.js
    - yarn install
    - git clone https://github.com/VerusCoin/verus-login-consent-client.git
    - cd verus-login-consent-client
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-login-consent-client
    - cp build/* ../assets/plugins/builtin/verus-login-consent-client
    - cd ..
    - rm -rf verus-login-consent-client
    - git clone https://github.com/VerusCoin/verus-pbaas-visualizer.git
    - cd verus-pbaas-visualizer
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-pbaas-visualizer
    - cp build/* ../assets/plugins/builtin/verus-pbaas-visualizer
    - cd ..
    - rm -rf verus-pbaas-visualizer
  script:
    - yarn run dist
    - cd dist
    - gsutil cp ${VERUS_APPIMAGE_X64} $STAGING/Verus-Desktop/$CI_COMMIT_REF_NAME/${VERUS_VERSION}/

build:linux:arm64:
  tags: [ "Verus Desktop" ]
  image: asherd/agama-builder
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    PIRATE_CLI_PACKAGE: pirate-cli-aarch64-v${PIRATE_VERSION}.zip
    PIRATE_CLI_SHA256: c6a3b13881155fb11a8743a9d319254a0ca70f99c14382fb28384446fffe52c5
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_LINUX="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Linux/Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/linux64/verusd
    - mkdir -p assets/bin/linux64/pirated
    - gsutil cp $STAGING/$VERUS_CLI_LINUX .
    - tar -xzvf Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz --strip=1 --directory assets/bin/linux64/verusd
    - rm Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz
    - wget ${PIRATE_DOWNLOAD_URL}/v${PIRATE_VERSION}/${PIRATE_CLI_PACKAGE}
    - echo "${PIRATE_CLI_SHA256} ${PIRATE_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - unzip ${PIRATE_CLI_PACKAGE} -d assets/bin/linux64/pirated
    - rm ${PIRATE_CLI_PACKAGE}
    - sed -i "s/process.env.INFURA_PROJECT_ID/'${INFURA_PROJECT_ID}'/g" keys/infura.js
    - sed -i "s/process.env.ETHERSCAN_API_KEY/'${ETHERSCAN_KEY}'/g" keys/etherscan.js
    - yarn install
    - git clone https://github.com/VerusCoin/verus-login-consent-client.git
    - cd verus-login-consent-client
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-login-consent-client
    - cp build/* ../assets/plugins/builtin/verus-login-consent-client
    - cd ..
    - rm -rf verus-login-consent-client
    - git clone https://github.com/VerusCoin/verus-pbaas-visualizer.git
    - cd verus-pbaas-visualizer
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-pbaas-visualizer
    - cp build/* ../assets/plugins/builtin/verus-pbaas-visualizer
    - cd ..
    - rm -rf verus-pbaas-visualizer
  script:
    - yarn run dist --arm64
    - cd dist
    - gsutil cp ${VERUS_APPIMAGE_ARM64} $STAGING/Verus-Desktop/$CI_COMMIT_REF_NAME/${VERUS_VERSION}/
########################################################################################################################
####END####                                              LINUX                                               ####END####
########################################################################################################################
####START####                                           WINDOWS                                            ####START####
########################################################################################################################
build:windows:
  tags: [ "Verus Desktop" ]
  stage: build
  image: asherd/agama-builder:windows
  variables:
    DOCKER_DRIVER: overlay2
    KOMODO_CLI_PACKAGE: komodo-${KOMODO_VERSION}-win.zip
    KOMODO_CLI_SHA256: 0b36821ebccdaf6bc060dc31083e6d8f48f7f8bc35e519b127bf1ccc05cf9890
    PIRATE_CLI_PACKAGE: pirate-cli-windows-v${PIRATE_VERSION}.zip
    PIRATE_CLI_SHA256: deb338bf2bcabfdb32be3c13dfaed78d83749fbae9d3985e47cb001ff058bb3f
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_WINDOWS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Windows/Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/win64/komodod
    - mkdir -p assets/bin/win64/pirated
    - wget ${KOMODO_DOWNLOAD_URL}/v${KOMODO_VERSION}/${KOMODO_CLI_PACKAGE}
    - echo "${KOMODO_CLI_SHA256} ${KOMODO_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - unzip -j ${KOMODO_CLI_PACKAGE} komodod.exe -d assets/bin/win64/komodod
    - unzip -j ${KOMODO_CLI_PACKAGE} komodo-cli.exe -d assets/bin/win64/komodod
    - unzip -j ${KOMODO_CLI_PACKAGE} wallet-utility.exe -d assets/bin/win64/komodod
    - rm ${KOMODO_CLI_PACKAGE}
    - gsutil cp $STAGING/$VERUS_CLI_WINDOWS .
    - unzip -qq Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip -d assets/bin/win64
    - mv assets/bin/win64/verus-cli assets/bin/win64/verusd
    - rm Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip
    - wget ${PIRATE_DOWNLOAD_URL}/v${PIRATE_VERSION}/${PIRATE_CLI_PACKAGE}
    - echo "${PIRATE_CLI_SHA256} ${PIRATE_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - unzip ${PIRATE_CLI_PACKAGE} -d assets/bin/win64/pirated
    - rm ${PIRATE_CLI_PACKAGE}
    - sed -i "s/process.env.INFURA_PROJECT_ID/'${INFURA_PROJECT_ID}'/g" keys/infura.js
    - sed -i "s/process.env.ETHERSCAN_API_KEY/'${ETHERSCAN_KEY}'/g" keys/etherscan.js
    - yarn install
    - git clone https://github.com/VerusCoin/verus-login-consent-client.git
    - cd verus-login-consent-client
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-login-consent-client
    - cp build/* ../assets/plugins/builtin/verus-login-consent-client
    - cd ..
    - rm -rf verus-login-consent-client
    - git clone https://github.com/VerusCoin/verus-pbaas-visualizer.git
    - cd verus-pbaas-visualizer
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-pbaas-visualizer
    - cp build/* ../assets/plugins/builtin/verus-pbaas-visualizer
    - cd ..
    - rm -rf verus-pbaas-visualizer
  script:
    - yarn run dist-win
    - cd dist
    - gsutil cp ${VERUS_WINDOWS_NSIS} $STAGING/Verus-Desktop/$CI_COMMIT_REF_NAME/${VERUS_VERSION}/

########################################################################################################################
####END####                                             WINDOWS                                              ####END####
########################################################################################################################
####START####                                            MACOS                                             ####START####
########################################################################################################################
build:mac:
  stage: build
  tags: ["Ventura"]
  variables:
    KOMODO_CLI_PACKAGE: komodo-${KOMODO_VERSION}-mac.zip
    KOMODO_CLI_SHA256: 1a092af97b34f4e2ea99b95a91599fc4fdca3881c7e3afa468a5df043a460694
    PIRATE_CLI_PACKAGE: pirate-cli-MacOS-v${PIRATE_VERSION}.zip
    PIRATE_CLI_SHA256: c20a761c36e494cd2b19237162881bb0dcdae24e6eec996072cc5ee7135e8362
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_MACOS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/MacOS/Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz";
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - gsutil cp $STAGING/$VERUS_CLI_MACOS .
    - mkdir -p assets/bin/osx/verusd
    - mkdir -p assets/bin/osx/komodod
    - mkdir -p assets/bin/osx/pirated
    - tar -xzf Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz --strip=1 --directory assets/bin/osx/verusd
    - rm Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz
    - wget ${KOMODO_DOWNLOAD_URL}/v${KOMODO_VERSION}/${KOMODO_CLI_PACKAGE}
    - echo "${KOMODO_CLI_SHA256} ${KOMODO_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - tar -xzvf ${KOMODO_CLI_PACKAGE} --directory assets/bin/osx/komodod
    - rm ${KOMODO_CLI_PACKAGE}
    - wget ${PIRATE_DOWNLOAD_URL}/v${PIRATE_VERSION}/${PIRATE_CLI_PACKAGE}
    - echo "${PIRATE_CLI_SHA256} ${PIRATE_CLI_PACKAGE}" | sha256sum -c - || { echo "SHA-256 checksum does not match. Exiting."; exit 1; }
    - unzip ${PIRATE_CLI_PACKAGE} -d assets/bin/osx/pirated
    - rm ${PIRATE_CLI_PACKAGE}
    - sed -i -e "s/process.env.INFURA_PROJECT_ID/'${INFURA_PROJECT_ID}'/g" keys/infura.js
    - sed -i -e "s/process.env.ETHERSCAN_API_KEY/'${ETHERSCAN_KEY}'/g" keys/etherscan.js
    - yarn install
    - git clone https://github.com/VerusCoin/verus-login-consent-client.git
    - cd verus-login-consent-client
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-login-consent-client
    - cp build/* ../assets/plugins/builtin/verus-login-consent-client
    - cd ..
    - rm -rf verus-login-consent-client
    - git clone https://github.com/VerusCoin/verus-pbaas-visualizer.git
    - cd verus-pbaas-visualizer
    - yarn install
    - yarn run build
    - mkdir -p ../assets/plugins/builtin/verus-pbaas-visualizer
    - cp build/* ../assets/plugins/builtin/verus-pbaas-visualizer
    - cd ..
    - rm -rf verus-pbaas-visualizer
  script:
    - export USE_HARD_LINKS=false
    - yarn run dist
    - cd dist
    - gsutil cp ${VERUS_MACOS} $STAGING/Verus-Desktop/$CI_COMMIT_REF_NAME/${VERUS_VERSION}/
